version: "3"
services: 
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.prod
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.prod
        ports: 
            - 80:80