FROM node:14

WORKDIR /server

COPY package*.json ./
COPY src/ ./src
COPY tsconfig.json .
COPY serviceAccountKey.json .

RUN npm i
RUN npm run build

ENV NODE_ENV=production

ENTRYPOINT [ "npm", "run", "start" ]