FROM node:14

WORKDIR /server

COPY package*.json ./
COPY src/ ./src
COPY tsconfig.json .
COPY serviceAccountKey.json .
COPY .env ./

RUN npm i
RUN npm run build

COPY src/handlebars/templates/ ./build/handlebars/templates/

ENV NODE_ENV=production

ENTRYPOINT [ "npm", "run", "start" ]